/* =============================================================================
 * d1/make-seed.js — generate d1/seed.sql from data/db.json
 * =============================================================================
 * Phase A migration: lifts the bundled seed content (the Lessons directory,
 * organizers, events, meta) into the D1 `docs` table.
 *
 * Emits SQL rather than calling the REST API so the seed can be applied with
 * `wrangler d1 execute --file=` on the existing OAuth login — no API token
 * needed, and the exact statements are reviewable before they run.
 *
 *   node d1/make-seed.js
 *   CLOUDFLARE_ACCOUNT_ID=... wrangler d1 execute btb-prod --remote --file=d1/seed.sql
 *
 * Idempotent: every row is an upsert keyed on (collection,id), so re-running is
 * safe and will not duplicate the directory.
 *
 * NOTE the key remap: the JSON file stores organizers under the legacy
 * `teachers` key (see JSON_KEYS in store.js). D1 uses the real collection name
 * `organizers`, matching the Firestore backend.
 * ========================================================================== */

'use strict';

const fs = require('fs');
const path = require('path');

const db = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', 'db.json'), 'utf8'));

// jsonKey -> D1 collection name
const COLLECTIONS = {
  studios: 'studios',
  teachers: 'organizers',
  events: 'events',
  threads: 'threads',
  newbies: 'newbies',
  volunteers: 'volunteers',
  checkins: 'checkins',
  messages: 'messages',
};

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

const NOW = new Date().toISOString();
const lines = [
  '-- GENERATED by d1/make-seed.js — do not edit by hand.',
  '-- Source: data/db.json  |  Generated: ' + NOW,
  '-- Upserts, so re-running is safe.',
  '',
];

let total = 0;
for (const [jsonKey, coll] of Object.entries(COLLECTIONS)) {
  const rows = db[jsonKey] || [];
  if (!rows.length) { lines.push(`-- ${coll}: 0 rows, nothing to seed`); continue; }
  lines.push(`-- ${coll}: ${rows.length} row(s)`);
  for (const doc of rows) {
    if (!doc || !doc.id) { console.warn(`skipping id-less row in ${jsonKey}`); continue; }
    lines.push(
      'INSERT INTO docs (collection, id, json, updatedAt) VALUES (' +
      `${q(coll)}, ${q(doc.id)}, ${q(JSON.stringify(doc))}, ${q(NOW)}) ` +
      'ON CONFLICT(collection, id) DO UPDATE SET json = excluded.json, updatedAt = excluded.updatedAt;',
    );
    total++;
  }
  lines.push('');
}

// meta is a single `content` doc (mirrors the Firestore backend's meta/content),
// NOT a collection of rows. Without this the footer pages (updates/ideas/todos)
// would render empty once D1 takes over.
const meta = {
  updates: (db.meta && db.meta.updates) || [],
  ideas: (db.meta && db.meta.ideas) || [],
  todos: (db.meta && db.meta.todos) || [],
};
lines.push(`-- meta: content doc (${meta.updates.length} updates, ${meta.ideas.length} ideas, ${meta.todos.length} todos)`);
lines.push(
  'INSERT INTO docs (collection, id, json, updatedAt) VALUES (' +
  `'meta', 'content', ${q(JSON.stringify(meta))}, ${q(NOW)}) ` +
  'ON CONFLICT(collection, id) DO UPDATE SET json = excluded.json, updatedAt = excluded.updatedAt;',
);
total++;

fs.writeFileSync(path.join(__dirname, 'seed.sql'), lines.join('\n') + '\n');
console.log(`wrote d1/seed.sql — ${total} upsert(s)`);
